export const arrData = [
    {
        "time": "2024-03-27T10:46:00Z",
        "values": {
          "cloudBase": 0.18,
          "cloudCeiling": 0.18,
          "cloudCover": 100,
          "dewPoint": 2.77,
          "freezingRainIntensity": 0,
          "humidity": 81,
          "precipitationProbability": 0,
          "pressureSurfaceLevel": 1018.03,
          "rainIntensity": 0,
          "sleetIntensity": 0,
          "snowIntensity": 0,
          "temperature": 5.79,
          "temperatureApparent": 5.79,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 13.67,
          "weatherCode": 1001,
          "windDirection": 26.29,
          "windGust": 2.22,
          "windSpeed": 1.85
        }
      },
      {
        "time": "2024-03-27T10:46:00Z",
        "values": {
          "cloudBase": 0.18,
          "cloudCeiling": 0.18,
          "cloudCover": 100,
          "dewPoint": 2.77,
          "freezingRainIntensity": 0,
          "humidity": 81,
          "precipitationProbability": 0,
          "pressureSurfaceLevel": 1018.03,
          "rainIntensity": 0,
          "sleetIntensity": 0,
          "snowIntensity": 0,
          "temperature": 5.79,
          "temperatureApparent": 5.79,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 13.67,
          "weatherCode": 1001,
          "windDirection": 26.29,
          "windGust": 2.22,
          "windSpeed": 1.85
        }
      }
];


export const dummyData = {
    "data": {
      "time": "2024-03-27T10:04:00Z",
      "values": {
        "cloudBase": 0.13,
        "cloudCeiling": 0.13,
        "cloudCover": 100,
        "dewPoint": 5.69,
        "freezingRainIntensity": 0,
        "humidity": 93,
        "precipitationProbability": 0,
        "pressureSurfaceLevel": 999.26,
        "rainIntensity": 0,
        "sleetIntensity": 0,
        "snowIntensity": 0,
        "temperature": 6.88,
        "temperatureApparent": 6.88,
        "uvHealthConcern": 0,
        "uvIndex": 0,
        "visibility": 14.87,
        "weatherCode": 1001,
        "windDirection": 148.69,
        "windGust": 5.38,
        "windSpeed": 3.69
      }
    },
    "location": {
      "lat": 43.653480529785156,
      "lon": -79.3839340209961,
      "name": "Old Toronto, Toronto, Golden Horseshoe, Ontario, Canada",
      "type": "administrative"
    }
  };

  export const objData = {
    "timelines": {
      "minutely": [
        {
          "time": "2024-03-27T10:13:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.81,
            "freezingRainIntensity": 0,
            "humidity": 84,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.51,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.19,
            "temperatureApparent": 5.19,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 15.25,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.5,
            "windSpeed": 1.5
          }
        },
        {
          "time": "2024-03-27T10:14:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.81,
            "freezingRainIntensity": 0,
            "humidity": 83.91,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.5,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.21,
            "temperatureApparent": 5.21,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 15.2,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.81,
            "windSpeed": 1.51
          }
        },
        {
          "time": "2024-03-27T10:15:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.81,
            "freezingRainIntensity": 0,
            "humidity": 83.82,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.48,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.22,
            "temperatureApparent": 5.22,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 15.15,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.83,
            "windSpeed": 1.52
          }
        },
        {
          "time": "2024-03-27T10:16:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.81,
            "freezingRainIntensity": 0,
            "humidity": 83.73,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.47,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.24,
            "temperatureApparent": 5.24,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 15.11,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.84,
            "windSpeed": 1.53
          }
        },
        {
          "time": "2024-03-27T10:17:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.81,
            "freezingRainIntensity": 0,
            "humidity": 83.64,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.45,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.26,
            "temperatureApparent": 5.26,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 15.06,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.85,
            "windSpeed": 1.54
          }
        },
        {
          "time": "2024-03-27T10:18:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.81,
            "freezingRainIntensity": 0,
            "humidity": 83.55,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.44,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.28,
            "temperatureApparent": 5.28,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 15.01,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.86,
            "windSpeed": 1.55
          }
        },
        {
          "time": "2024-03-27T10:19:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.8,
            "freezingRainIntensity": 0,
            "humidity": 83.45,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.43,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.3,
            "temperatureApparent": 5.3,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.96,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.88,
            "windSpeed": 1.56
          }
        },
        {
          "time": "2024-03-27T10:20:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.8,
            "freezingRainIntensity": 0,
            "humidity": 83.36,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.41,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.31,
            "temperatureApparent": 5.31,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.91,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.89,
            "windSpeed": 1.57
          }
        },
        {
          "time": "2024-03-27T10:21:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.8,
            "freezingRainIntensity": 0,
            "humidity": 83.27,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.4,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.33,
            "temperatureApparent": 5.33,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.87,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.9,
            "windSpeed": 1.59
          }
        },
        {
          "time": "2024-03-27T10:22:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.8,
            "freezingRainIntensity": 0,
            "humidity": 83.18,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.38,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.35,
            "temperatureApparent": 5.35,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.82,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.92,
            "windSpeed": 1.6
          }
        },
        {
          "time": "2024-03-27T10:23:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.8,
            "freezingRainIntensity": 0,
            "humidity": 83.09,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.37,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.37,
            "temperatureApparent": 5.37,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.77,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.93,
            "windSpeed": 1.61
          }
        },
        {
          "time": "2024-03-27T10:24:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.8,
            "freezingRainIntensity": 0,
            "humidity": 83,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.35,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.39,
            "temperatureApparent": 5.39,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.72,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.94,
            "windSpeed": 1.62
          }
        },
        {
          "time": "2024-03-27T10:25:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.8,
            "freezingRainIntensity": 0,
            "humidity": 82.91,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.34,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.4,
            "temperatureApparent": 5.4,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.67,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.95,
            "windSpeed": 1.63
          }
        },
        {
          "time": "2024-03-27T10:26:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.79,
            "freezingRainIntensity": 0,
            "humidity": 82.82,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.32,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.42,
            "temperatureApparent": 5.42,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.63,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.97,
            "windSpeed": 1.64
          }
        },
        {
          "time": "2024-03-27T10:27:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.79,
            "freezingRainIntensity": 0,
            "humidity": 82.73,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.31,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.44,
            "temperatureApparent": 5.44,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.58,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.98,
            "windSpeed": 1.65
          }
        },
        {
          "time": "2024-03-27T10:28:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.79,
            "freezingRainIntensity": 0,
            "humidity": 82.64,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.29,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.46,
            "temperatureApparent": 5.46,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.53,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 1.99,
            "windSpeed": 1.66
          }
        },
        {
          "time": "2024-03-27T10:29:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.79,
            "freezingRainIntensity": 0,
            "humidity": 82.54,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.28,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.48,
            "temperatureApparent": 5.48,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.48,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 2.01,
            "windSpeed": 1.67
          }
        },
        {
          "time": "2024-03-27T10:30:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.79,
            "freezingRainIntensity": 0,
            "humidity": 82.45,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.26,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.5,
            "temperatureApparent": 5.5,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.43,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 2.02,
            "windSpeed": 1.68
          }
        },
        {
          "time": "2024-03-27T10:31:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.79,
            "freezingRainIntensity": 0,
            "humidity": 82.36,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.25,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.51,
            "temperatureApparent": 5.51,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.39,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 2.03,
            "windSpeed": 1.69
          }
        },
        {
          "time": "2024-03-27T10:32:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.79,
            "freezingRainIntensity": 0,
            "humidity": 82.27,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.23,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.53,
            "temperatureApparent": 5.53,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.34,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 2.04,
            "windSpeed": 1.7
          }
        },
        {
          "time": "2024-03-27T10:33:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.79,
            "freezingRainIntensity": 0,
            "humidity": 82.18,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.22,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.55,
            "temperatureApparent": 5.55,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.29,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 2.06,
            "windSpeed": 1.71
          }
        },
        {
          "time": "2024-03-27T10:34:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.78,
            "freezingRainIntensity": 0,
            "humidity": 82.09,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.2,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.57,
            "temperatureApparent": 5.57,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.24,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 2.07,
            "windSpeed": 1.72
          }
        },
        {
          "time": "2024-03-27T10:35:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.78,
            "freezingRainIntensity": 0,
            "humidity": 82,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.19,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.59,
            "temperatureApparent": 5.59,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.19,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 2.08,
            "windSpeed": 1.74
          }
        },
        {
          "time": "2024-03-27T10:36:00Z",
          "values": {
            "cloudBase": 0.3,
            "cloudCeiling": 0.3,
            "cloudCover": 100,
            "dewPoint": 2.78,
            "freezingRainIntensity": 0,
            "humidity": 81.91,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.18,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.6,
            "temperatureApparent": 5.6,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.15,
            "weatherCode": 1001,
            "windDirection": 24.69,
            "windGust": 2.1,
            "windSpeed": 1.75
          }
        },
        {
          "time": "2024-03-27T10:37:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.78,
            "freezingRainIntensity": 0,
            "humidity": 81.82,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.16,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.62,
            "temperatureApparent": 5.62,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.1,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.11,
            "windSpeed": 1.76
          }
        },
        {
          "time": "2024-03-27T10:38:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.78,
            "freezingRainIntensity": 0,
            "humidity": 81.73,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.15,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.64,
            "temperatureApparent": 5.64,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14.05,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.12,
            "windSpeed": 1.77
          }
        },
        {
          "time": "2024-03-27T10:39:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.78,
            "freezingRainIntensity": 0,
            "humidity": 81.63,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.13,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.66,
            "temperatureApparent": 5.66,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 14,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.13,
            "windSpeed": 1.78
          }
        },
        {
          "time": "2024-03-27T10:40:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.78,
            "freezingRainIntensity": 0,
            "humidity": 81.54,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.12,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.68,
            "temperatureApparent": 5.68,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 13.96,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.15,
            "windSpeed": 1.79
          }
        },
        {
          "time": "2024-03-27T10:41:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.77,
            "freezingRainIntensity": 0,
            "humidity": 81.45,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.1,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.69,
            "temperatureApparent": 5.69,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 13.91,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.16,
            "windSpeed": 1.8
          }
        },
        {
          "time": "2024-03-27T10:42:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.77,
            "freezingRainIntensity": 0,
            "humidity": 81.36,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.09,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.71,
            "temperatureApparent": 5.71,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 13.86,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.17,
            "windSpeed": 1.81
          }
        },
        {
          "time": "2024-03-27T10:43:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.77,
            "freezingRainIntensity": 0,
            "humidity": 81.27,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.07,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.73,
            "temperatureApparent": 5.73,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 13.81,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.19,
            "windSpeed": 1.82
          }
        },
        {
          "time": "2024-03-27T10:44:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.77,
            "freezingRainIntensity": 0,
            "humidity": 81.18,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.06,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.75,
            "temperatureApparent": 5.75,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 13.76,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.2,
            "windSpeed": 1.83
          }
        },
        {
          "time": "2024-03-27T10:45:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.77,
            "freezingRainIntensity": 0,
            "humidity": 81.09,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.04,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.77,
            "temperatureApparent": 5.77,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 13.72,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.21,
            "windSpeed": 1.84
          }
        },
        {
          "time": "2024-03-27T10:46:00Z",
          "values": {
            "cloudBase": 0.18,
            "cloudCeiling": 0.18,
            "cloudCover": 100,
            "dewPoint": 2.77,
            "freezingRainIntensity": 0,
            "humidity": 81,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 1018.03,
            "rainIntensity": 0,
            "sleetIntensity": 0,
            "snowIntensity": 0,
            "temperature": 5.79,
            "temperatureApparent": 5.79,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 13.67,
            "weatherCode": 1001,
            "windDirection": 26.29,
            "windGust": 2.22,
            "windSpeed": 1.85
          }
        }]}}